Refactor deployment workflow to print current working directory during build and list contents of 'out' directory before deploy

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -88,7 +88,7 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
-      - name: Print current working directory
+      - name: Print current working directory during build
         run: pwd
       
       - name: Set up Node.js
@@ -137,7 +137,7 @@ jobs:
         run: |
           echo "Listing contents of 'out' directory before deploy..."
           pwd # Imprimir diretório atual
-          ls -la ./tdw-aleluia/out || echo "'out' directory not found!"
+          ls -la /home/runner/work/aula2/aula2/tdw-aleluia/out || echo "'out' directory not found!"
 
       - name: Set up Node.js
         uses: actions/setup-node@v3
@@ -145,4 +145,4 @@ jobs:
           node-version: "22"
 
       - name: Deploy to Netlify
-        run: npx netlify-cli deploy --site lucky-semifreddo-6de349.netlify.app --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --prod --dir=./tdw-aleluia/out
+        run: npx netlify-cli deploy --site lucky-semifreddo-6de349.netlify.app --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --prod --dir=/home/runner/work/aula2/aula2/tdw-aleluia/out
