Refactor deployment workflow to update Node.js version and cache npm dependencies

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,23 +20,25 @@ jobs:
       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
-          node-version: '22'
+          node-version: '18' # Versão mais estável
 
-      - name: Install dependencies
-        run: npm install
-        working-directory: ./tdw-aleluia
-
-  run-tests:
-    runs-on: ubuntu-latest
-    needs: install-dependencies
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-
-      - name: Set up Node.js
-        uses: actions/setup-node@v3
+      - name: Cache npm
+        uses: actions/cache@v3
         with:
-          node-version: '22'
+          path: ~/.npm
+          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-npm-
+
+      - name: Set npm config for timeouts
+        run: |
+          npm config set fetch-retries 5
+          npm config set fetch-retry-mintimeout 20000
+          npm config set fetch-retry-maxtimeout 120000
+
+      - name: Install sharp manually
+        run: npm install sharp --unsafe-perm
+        working-directory: ./tdw-aleluia
 
       - name: Install dependencies
         run: npm install
@@ -62,7 +64,7 @@ jobs:
 
   linting:
     runs-on: ubuntu-latest
-    needs: run-tests
+    needs: install-dependencies  # Corrigido para depender da instalação
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
@@ -137,7 +139,7 @@ jobs:
         run: |
           echo "Listing contents of 'out' directory before deploy..."
           pwd # Imprimir diretório atual
-          ls -la /home/runner/work/aula2/aula2/tdw-aleluia/out || echo "'out' directory not found!"
+          ls -la ./tdw-aleluia/out || echo "'out' directory not found!"
 
       - name: Set up Node.js
         uses: actions/setup-node@v3
@@ -145,4 +147,4 @@ jobs:
           node-version: "22"
 
       - name: Deploy to Netlify
-        run: npx netlify-cli deploy --site lucky-semifreddo-6de349.netlify.app --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --prod --dir=/home/runner/work/aula2/aula2/tdw-aleluia/out
+        run: npx netlify-cli deploy --site lucky-semifreddo-6de349.netlify.app --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --prod --dir=./tdw-aleluia/out
